# Generated by Django 3.1.7 on 2021-03-11 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('repository_link', models.URLField(blank=True)),
                ('members', models.ManyToManyField(to='userapp.DefaultUser')),
            ],
        ),
        migrations.CreateModel(
            name='TODO_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actual_sign', models.CharField(choices=[('ACT', 'Active'), ('CLD', 'Closed')], default='CLD', max_length=3)),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.defaultuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project')),
            ],
        ),
    ]
