# Generated by Django 3.1.7 on 2021-04-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
